### ISSUE TITLE
Route discrepancy between Webpack 5 and Webpack 4 (NextJS)

### ISSUE THREAD

**Issue by ParamagicDev** [honeybadger-io/honeybadger-webpack#293] opened 2021-03-20 22:12 UTC
## What are the steps to reproduce this issue?

1. Go to my current branch here for NextJS with honeybadger
2. Clone it
3. Run `yarn build`
4. Then go to set the Webpack version to 5 under the `future` flag.
5. Rerun `yarn build`

## What happens?

There is a route discrepancy between Webpack 4 and Webpack 5 and im not 100% if its due to the Webpack plugin or due to route generation by Next.js itself.

## What were you expecting to happen?

Filepaths should be the same

### Webpack 4

```bash
➜  nextjs-example-with-honeybadger git:(chore/upgrade-nextjs) ✗ yarn build
yarn run v1.22.10
$ next build
info  - Loaded env from /Users/konnorrogers/projects/oss/nextjs-example-with-honeybadger/.env
info  - Creating an optimized production build .

info  - Creating an optimized production build ..

info  - Creating an optimized production build ...Uploaded init-server.js.js.map to Honeybadger API
Uploaded pages/server/test3.js.map to Honeybadger API
Uploaded pages/_error.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test2-a19a76cdcbac88e9a992.js.map to Honeybadger API
Uploaded pages/client/test8.js.map to Honeybadger API
Uploaded on-error-server.js.js.map to Honeybadger API
Uploaded pages/server/test4.js.map to Honeybadger API
info  - Creating an optimized production build .Uploaded static/chunks/pages/server/test3-feba04b864835b3d16a3.js.map to Honeybadger API
Uploaded pages/client/test6.js.map to Honeybadger API
Uploaded static/chunks/webpack-50bee04d1dc61f8adf5b.js.map to Honeybadger API
Uploaded pages/client/test7.js.map to Honeybadger API
Uploaded static/chunks/pages/server/test2-f284cc82ecdce9bf4ddc.js.map to Honeybadger API
Uploaded pages/client/test2.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test3-18a0f0bf89a5d2098a1d.js.map to Honeybadger API
Uploaded pages/client/test1.js.map to Honeybadger API
Uploaded pages/_app.js.map to Honeybadger API
Uploaded pages/server/test2.js.map to Honeybadger API
Uploaded static/chunks/pages/_error-9c356f6811401fe8c466.js.map to Honeybadger API
Uploaded static/chunks/pages/server/test4-5c79c69de9744289db43.js.map to Honeybadger API
Uploaded pages/client/test5.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test6-5ebd4dfe403d7dad7c60.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test1-594de535bd88331c398c.js.map to Honeybadger API
Uploaded pages/server/test1.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test5-f863a09060a7d930c2a7.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test4-5578ee454f71ce9486e5.js.map to Honeybadger API
Uploaded static/chunks/3ef630e34cd10ba68f9d468ac363ff81c534e1e9.b34bca09bc5b938f8f6a.js.map to Honeybadger API
Uploaded pages/client/test3.js.map to Honeybadger API
Uploaded pages/client/test4.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test8-992da195954cdcc98368.js.map to Honeybadger API
Uploaded static/chunks/pages/server/test1-ea3ac3406c6341926a83.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test7-fa7fae48a5b6992b6a4b.js.map to Honeybadger API
info  - Creating an optimized production build ..Uploaded static/chunks/5b6f950a52454da5f4b23d4c6766dc18806479d2.ebefd935aa9eadf7826f.js.map to Honeybadger API
Uploaded static/chunks/polyfills-ad30d1320810fa304e64.js.map to Honeybadger API
Uploaded static/chunks/pages/_app-2dbd3b2c4e04cbd5636c.js.map to Honeybadger API
Uploaded static/chunks/pages/index-a401cd124aef398c560e.js.map to Honeybadger API
Uploaded static/chunks/b1542cc239bf56c8a14913c0a930efe682b5cf86.407db31abe66d51137a0.js.map to Honeybadger API
Uploaded pages/_document.js.map to Honeybadger API
Uploaded pages/index.js.map to Honeybadger API
Uploaded static/chunks/main-5f5a175c650de61ce3fe.js.map to Honeybadger API
Uploaded static/chunks/framework.e2fe4ae6b85b1c7a6eb1.js.map to Honeybadger API
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (6/6)
info  - Finalizing page optimization

Page                                                           Size     First Load JS
┌ ○ /                                                          2.69 kB        75.5 kB
├   /_app                                                      0 B            72.9 kB
├ λ /404                                                       3.78 kB        76.6 kB
├ λ /client/test1                                              316 B          73.2 kB
├ λ /client/test2                                              321 B          73.2 kB
├ λ /client/test3                                              324 B          73.2 kB
├ ○ /client/test4                                              305 B          73.2 kB
├ ○ /client/test5                                              336 B          73.2 kB
├ ○ /client/test6                                              319 B          73.2 kB
├ ○ /client/test7                                              600 B          73.5 kB
├ ○ /client/test8                                              356 B          73.2 kB
├ λ /server/test1                                              313 B          73.2 kB
├ λ /server/test2                                              320 B          73.2 kB
├ λ /server/test3                                              322 B          73.2 kB
└ λ /server/test4                                              322 B          73.2 kB
+ First Load JS shared by all                                  72.9 kB
  ├ chunks/3ef630e34cd10ba68f9d468ac363ff81c534e1e9.b34bca.js  11.3 kB
  ├ chunks/5b6f950a52454da5f4b23d4c6766dc18806479d2.ebefd9.js  2.47 kB
  ├ chunks/b1542cc239bf56c8a14913c0a930efe682b5cf86.407db3.js  7.34 kB
  ├ chunks/framework.e2fe4a.js                                 41.8 kB
  ├ chunks/main.5f5a17.js                                      6.67 kB
  ├ chunks/pages/_app.2dbd3b.js                                2.61 kB
  └ chunks/webpack.50bee0.js                                   751 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

✨  Done in 4.96s.
```

### Webpack 5

```bash
➜  nextjs-example-with-honeybadger git:(chore/upgrade-nextjs) ✗ yarn build
yarn run v1.22.10
$ next build
info  - Loaded env from /Users/konnorrogers/projects/oss/nextjs-example-with-honeybadger/.env
info  - Creating an optimized production build ..

info  - Creating an optimized production build ..Uploaded ../pages/client/test1.js.map to Honeybadger API
Uploaded ../pages/client/test8.js.map to Honeybadger API
Uploaded ../pages/server/test3.js.map to Honeybadger API
Uploaded ../pages/server/test2.js.map to Honeybadger API
Uploaded ../pages/server/test4.js.map to Honeybadger API
Uploaded ../chunks/webpack-runtime.js.map to Honeybadger API
Uploaded ../init-server.js.js.map to Honeybadger API
Uploaded ../pages/client/test7.js.map to Honeybadger API
Uploaded ../pages/_app.js.map to Honeybadger API
Uploaded ../pages/_error.js.map to Honeybadger API
Uploaded ../pages/server/test1.js.map to Honeybadger API
Uploaded ../pages/client/test4.js.map to Honeybadger API
Uploaded ../on-error-server.js.js.map to Honeybadger API
Uploaded ../pages/client/test5.js.map to Honeybadger API
Uploaded ../pages/index.js.map to Honeybadger API
Uploaded ../pages/client/test2.js.map to Honeybadger API
Uploaded ../pages/client/test6.js.map to Honeybadger API
Uploaded ../pages/client/test3.js.map to Honeybadger API
Uploaded ../pages/_document.js.map to Honeybadger API
info  - Creating an optimized production build .

info  - Creating an optimized production build ...Uploaded static/chunks/pages/client/test7-7eef46b289e0cd716287.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test1-d5dbc5e9e3d9758b7fdb.js.map to Honeybadger API
Uploaded static/chunks/webpack-979ec0efe4c381fc113e.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test2-950838ab70a7bda24dd5.js.map to Honeybadger API
info  - Creating an optimized production build .Uploaded static/chunks/pages/client/test4-d91624637315e6471873.js.map to Honeybadger API
Uploaded static/chunks/pages/_error-3457dee77bc68957e12f.js.map to Honeybadger API
Uploaded static/chunks/pages/_app-54084b4f3fb701a0af5c.js.map to Honeybadger API
Uploaded static/chunks/pages/index-93843e1717f30d741adb.js.map to Honeybadger API
Uploaded static/chunks/433-6b09765603c68f4f5e79.js.map to Honeybadger API
Uploaded static/chunks/polyfills-9ae8f68a2a1765de3320.js.map to Honeybadger API
Uploaded static/chunks/pages/server/test1-92f15b67061dc75ded28.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test5-5fc214b0f8286ccacef0.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test8-9e1a64ad2c42237a3b60.js.map to Honeybadger API
Uploaded static/chunks/pages/server/test2-85ae70b53e9080f80ef1.js.map to Honeybadger API
Uploaded static/chunks/pages/server/test4-3ad11a18768e5970c67e.js.map to Honeybadger API
Uploaded static/chunks/pages/server/test3-9fd817dd0b8f3619295e.js.map to Honeybadger API
Uploaded static/chunks/main-c693a8a568dfe21abd8f.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test3-c6b6380186094bf57f5d.js.map to Honeybadger API
Uploaded static/chunks/pages/client/test6-bf249e63cfdaa559f0fa.js.map to Honeybadger API
info  - Creating an optimized production build ..Uploaded static/chunks/456-1b05d7f9d7b7a30f0c07.js.map to Honeybadger API
Uploaded static/chunks/721-c6ad7c0ae0cda7307d82.js.map to Honeybadger API
Uploaded static/chunks/framework-92d0eaf9317d57d136ad.js.map to Honeybadger API
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (6/6)
info  - Finalizing page optimization

Page                             Size     First Load JS
┌ ○ /                            2.66 kB        75.8 kB
├   /_app                        0 B            73.1 kB
├ λ /404                         3.71 kB        76.8 kB
├ λ /client/test1                317 B          73.4 kB
├ λ /client/test2                326 B          73.4 kB
├ λ /client/test3                328 B          73.4 kB
├ ○ /client/test4                304 B          73.4 kB
├ ○ /client/test5                331 B          73.4 kB
├ ○ /client/test6                313 B          73.4 kB
├ ○ /client/test7                595 B          73.7 kB
├ ○ /client/test8                349 B          73.5 kB
├ λ /server/test1                320 B          73.4 kB
├ λ /server/test2                326 B          73.4 kB
├ λ /server/test3                326 B          73.4 kB
└ λ /server/test4                326 B          73.4 kB
+ First Load JS shared by all    73.1 kB
  ├ chunks/433.6b0976.js         11.2 kB
  ├ chunks/456.1b05d7.js         2.47 kB
  ├ chunks/721.c6ad7c.js         7.32 kB
  ├ chunks/framework.92d0ea.js   42 kB
  ├ chunks/main.c693a8.js        6.61 kB
  ├ chunks/pages/_app.54084b.js  2.48 kB
  └ chunks/webpack.979ec0.js     958 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

✨  Done in 11.40s.
```

## What versions are you using?
**Operating System:** MacOS big sur
**Package Version:** master branch

**Comment by ParamagicDev** [comment] 2021-03-20 22:13
Webpack 5 is still under the `future` flag in Next.js but figured I would have it documented here.

**Comment by joshuap** [comment] 2022-08-10 19:29
@subzero10 can you take a look at this and close it if it's no longer an issue?

**Comment by subzero10** [comment] 2022-08-11 15:58
Sure, I can do that! However, I'm not sure I understand the problem here. 
Are you referring to the below?

**v4**
```
Uploaded pages/index.js.map to Honeybadger API
```

**v5**
```
Uploaded ../pages/index.js.map to Honeybadger API
```

cc @joshuap @ParamagicDev

**Comment by joshuap** [comment] 2022-08-12 04:08
> Sure, I can do that! However, I'm not sure I understand the problem here. Are you referring to the below?
> 
> **v4**
> 
> ```
> Uploaded pages/index.js.map to Honeybadger API
> ```
> 
> **v5**
> 
> ```
> Uploaded ../pages/index.js.map to Honeybadger API
> ```
> 
> cc @joshuap @ParamagicDev

I'm not sure tbh, as long as the result in Honeybadger is the same, then it's probably fine?

**Comment by subzero10** [comment] 2022-08-12 11:14
OK. Then I guess what I have to do is make sure that source maps correctly point to the source, right?

**Comment by joshuap** [comment] 2022-08-12 17:44
> OK. Then I guess what I have to do is make sure that source maps correctly point to the source, right?

I wouldn't worry about checking the actual contents of the generated source maps—just make sure the plugin uploads them with the correct `minified_url`, etc. I'm also fine with just confirming the current test suite passes for Webpack 5, and close this PR. If something is really wrong, I'm sure we'll hear about it. :)

**Comment by ParamagicDev** [comment] 2022-08-12 19:19
I don't remember if anything was wrong here, I just remember being a worried about differing relative paths leading to different source map URLs.

**Comment by subzero10** [comment] 2022-08-19 09:53
I just tried this on a new project with webpack v5 and I can see the source maps uploaded and applied on the backend.

There is one problem I noticed though, the source map is off by a few lines. As you can see below, the `console.log` line is highlighted, but in reality the error is caused by the next executable line (not visible in the trace because it's line 15.
This is not a problem with Honeybadger, but with webpack and source map generation:
- https://github.com/webpack/webpack/issues/1487
- https://github.com/getsentry/sentry-javascript/issues/2701
- https://stackoverflow.com/questions/42413955/sourcemap-not-mapping-the-correct-line
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/5813382/185591757-0b805ecc-a6f4-4ff2-9c7b-eae9fcffbe8d.png">

**Closed by subzero10** 2022-08-19 09:53 UTC
